name: validate-helm

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  validate-helm:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: output.log is present
      run: |
        if [ ! -f output.log ]; then
          echo 'output.log is not present'
          echo 'Deploy helm chart to your `kind` cluster'
          echo 'Run command `kubectl get all,cm,secret,ing -A` and put the output in a file called `output.log` in a root of the repository'
          exit 1
        fi

    - name: MYSQL Dependency Present
      if: always()
      run: |
        if ! grep -q "name: mysql" .infrastructure/helm-chart/todoapp/Chart.yaml; then
          echo 'MYSQL dependency is not present'
          echo 'Inside the Chart.yaml file of todoapp chart, add lines'
          echo 'dependencies:'
          echo '- name: mysql'
          exit 1
        fi

    - name: Todoapp Chart Present
      if: always()
      run: |
        if [ ! -d .infrastructure/helm-chart/todoapp ]; then
          echo "Todoapp Chart is not present or named incorrectly"
          exit 1
        fi

    - name: MYSQL Chart Present
      if: always()
      run: |
        if [ ! -d .infrastructure/helm-chart/todoapp/charts/mysql ]; then
          echo "MYSQL Chart is not present or named incorrectly"
          exit 1
        fi

    - name: Helm Lint
      if: always()
      run: |
        helm lint .infrastructure/helm-chart/todoapp

    - name: Helm Template
      if: always()
      run: |
        helm template .infrastructure/helm-chart/todoapp -f .infrastructure/helm-chart/todoapp/values.yaml
        
    - uses: actions/setup-python@v5
      if: always()
      with:
        python-version: '3.10' 

    - name: Validate Output    
      if: always()
      run: |
        python .github/workflows/scripts/validate-output.py
      
